name: Zip Releases

on: [release, workflow_dispatch]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip files
        run: zip -r O3M.zip . -x ".git/*" ".github/*" "todo.md" ".gitignore"
      - uses: actions/upload-artifact@v1
        with:
          name: zip-release
          path: ${{ github.workspace }}/O3M.zip
